[package]
name = "roblox_random"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
webbrowser = "0.7"
dictionary2 = "1.0"
